#-------------------------------
# General Site Settings

title: Donnatto | A Developer's Blog
description: Un blog acerca del mundo de la tecnologia, creado con un enfoque apto para todos.
baseurl: ""
url: "https://blog.donnatto.me"


#-------------------------------
# About Section
author-name:   Edwin Dominguez
author-avatar: pic-donnatto.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/edwin.dom
linkedin: https://www.linkedin.com/in/edwin-dom/
github:   https://github.com/donnatto
instagram: https://www.instagram.com/donnatto_


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: blog-donnatto


#-------------------------------
# Instagram Feed
instafeed: true


#-------------------------------
# Google Analytics
google-analytics: UA-147369813-1


#-------------------------------
# Newsletter
# mailchimp:


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
